name: video_downloader_player
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_downloader: ^1.12.0
  flutter_vlc_player: ^7.4.3
  video_player: ^2.9.5
  path_provider: ^2.1.5
  rxdart: ^0.28.0
  pip: ^0.0.3
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  wakelock_windows: ^0.2.1